networks:
  inception:

services:
  nginx:
    build: ./requierments/nginx
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requierments/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_files:/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requierments/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wp_db:
    driver: local
  wp_files:
    driver: local