services:
  nginx:
    build: ./requierments/nginx
    container_name: nginx
    ports:
      - "4430:4430"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - common_wp_ng:/var/www/html
      - /run/php:/run/php
     # - /nginx/ssl:/etc/nginx/ssl

  wordpress:
    build: ./requierments/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"
    volumes:
      - common_wp_ng:/var/www/html
      - /run/php:/run/php

  mariadb:
    build: ./requierments/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    restart: always
    expose:
      - "3306"
    volumes:
      - /home/mgovinda/data/mariadb:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  common_wp_ng:
    driver: local
    driver_opts:
      type: none
      device: /home/mgovinda/data/wordpress
      o: bind
  database_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mgovinda/data/mariadb
      o: bind