version: "3.8"

services:
  nginx:
    build: ./srcs/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_files:var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    emv_file: .env
    volumes:
      -wp_files:/www/html
    networks:
      -inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
    restart: always
	
networks:
  inception:

volumes:
  wp_db:
    driver: local
  wp_files:
    driver: local