version: "3.8"

networks:
  inception:

services:
  nginx:
    build: ./requierments/nginx
    container_name: nginx
    ports:
      - "8443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requierments/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requierments/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    restart: always